# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to Github Packages

on:
  release:
    types: [published]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: setup .npmrc
        run: |
          echo "@qasirdev:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_PAT" >> .npmrc
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
         
      - name: clean & build & prod & publish
        run: |
          npm run clean:build:prod
          npm publish
